name: Hello  # ワークフロー名

on: push  # push イベント時に実行

jobs:
  hello:  # ジョブID
    runs-on: ubuntu-latest  # ランナー指定（run-on → runs-on）
    steps:  # setps → steps に修正
      - run: echo "hello, world"  # シェルコマンドの実行
      - uses: actions/checkout@v4  # リポジトリをチェックアウト
