name: Hello      #ワークフロー名
on: push        #イベント(プッシュ時に起動)
jobs:           #ジョブの定義
  hello:        #ジョブID
    run-on: ubuntu-latest  #ランナー(Ubuntuで実行)
    setps:                 #ステップの定義
      - run: echo "hello, world" #シェルコマンドの実行
      - uses: actions/checkout@v4 #アクションの呼び出し